services:  
  db:  
    image: postgres:13  
    environment:  
      - POSTGRES_USER=postgres  
      - POSTGRES_PASSWORD=password  
      - POSTGRES_DB=transcription  
    ports:  
      - '5432:5432'  
    volumes:  
      - db-data-dev:/var/lib/postgresql/data  
  
  redis:  
    image: redis:6  
    ports:  
      - '6379:6379'  
  
volumes:  
  db-data-dev:  