services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - '5001:5001'
    command: npm run dev  # Changed to use nodemon in dev mode
    environment:
      - PORT=5001
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=transcription
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_API_URL=${OPENAI_API_URL}
      - WHISPER_MODEL=whisper-large-v3-turbo
    depends_on:
      - db
      - redis
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - '3000:80'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  worker:
    build:
      context: .
      dockerfile: Dockerfile.backend
    command: npm run worker:dev
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=transcription
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_API_URL=${OPENAI_API_URL}
      - WHISPER_MODEL=whisper-large-v3-turbo
    depends_on:
      - db
      - redis
    volumes:
      - ./backend:/app
      - /app/node_modules
      
  db:  
    image: postgres:13  
    environment:  
      - POSTGRES_USER=postgres  
      - POSTGRES_PASSWORD=password  
      - POSTGRES_DB=transcription  
    volumes:  
      - db-data:/var/lib/postgresql/data  
  redis:  
    image: redis:6  
    ports:  
      - '6379:6379'
  
volumes:  
  db-data:  