# Dockerfile.frontend

# Build Stage
FROM node:20 AS build
WORKDIR /app
COPY frontend/package*.json ./
RUN npm install
COPY frontend/ ./
RUN npm run build

# Production Stage
FROM nginx:stable-alpine

# Copy the Nginx config
COPY nginx.conf /etc/nginx/nginx.conf

# Copy the built app
COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
