# Build Stage  
FROM node:16 AS build  
  
WORKDIR /app  
  
COPY frontend/package*.json ./  
RUN npm install  
  
COPY frontend/ ./  
  
RUN npm run build  
  
# Production Stage  
FROM nginx:stable-alpine  
  
COPY --from=build /app/build /usr/share/nginx/html  
  
EXPOSE 80  
  
CMD ["nginx", "-g", "daemon off;"]  